### ISSUE TITLE
As SpazioDati I want to log progress of ANAC_url_generator.js

### ISSUE THREAD

**Issue by lonlylocly** [synapta/public-contracts#15]
Say, every 1% of done urls write log message like this:
```
INFO Done 56%...
INFO Done 57%...
```
So to be able to tell that script is still going.

**Comment by lonlylocly** [comment]
Good to have also for `downloader.js` and `enricher.js`.

**Comment by alemela** [comment]
For now I've improved the first scrpit with: https://github.com/synapta/public-contracts/commit/76af03a636f058c0f82b21bef9bf6cafd33cec34
It creates a more debugging log file while the console still use progress bar.
