### ISSUE TITLE
As SpazioDati I want to stop waiting for gone websites

### ISSUE THREAD

**Issue by lonlylocly** [synapta/public-contracts#16]
Looks like we have information that some ip/website is not available.
```
ERROR,http://93.63.179.120/AVCP/2014/Z3D0EB9B45-20150123120933813.xml,connect ETIMEDOUT,0,1017856
ERROR,http://93.63.179.120/AVCP/2014/Z3F0D962BD-20150123090107938.xml,connect ETIMEDOUT,0,890627
ERROR,http://93.63.179.120/AVCP/2014/Z3F120B602-20150122170018438.xml,connect ETIMEDOUT,0,1017854
ERROR,http://93.63.179.120/AVCP/2014/Z400E3B55F-20150126101642438.xml,connect ETIMEDOUT,0,1017854
ERROR,http://93.63.179.120/AVCP/2014/Z410D8354B-201412241119588.xml,connect ETIMEDOUT,0,1017855
ERROR,http://93.63.179.120/AVCP/2014/Z4111A5BF3-20150122164145969.xml,connect ETIMEDOUT,0,1017855
ERROR,http://93.63.179.120/AVCP/2014/Z440FA4373-20150122112439422.xml,connect ETIMEDOUT,0,890627
ERROR,http://93.63.179.120/AVCP/2014/Z44109D413-20150123102107969.xml,connect ETIMEDOUT,0,1017854
ERROR,http://93.63.179.120/AVCP/2014/Z450D8DF03-20150115111005213.xml,connect ETIMEDOUT,0,1017854
ERROR,http://93.63.179.120/AVCP/2014/Z4512687FA-20150127104303031.xml,connect ETIMEDOUT,0,1017855
ERROR,http://93.63.179.120/AVCP/2014/Z470E6998D-20150126095814609.xml,connect ETIMEDOUT,0,1017855
ERROR,http://93.63.179.120/AVCP/2014/Z4710EE415-20150126111804266.xml,connect ETIMEDOUT,0,890627
```
If ANAC_url_generator.js have seen 3 ETIMEOUT for the same domain, stop trying to fetch documents from there. Drop them with different error (e.g. SITE_DOWN_DIDNT_TRY).

**Comment by federicomorando** [comment]
Ok, but I would make this configurable. PA website may be poor and down for long time. I would also like the option of trying again forever. 

On February 10, 2016 4:33:47 PM GMT+01:00, Nikolay Vasiliev <notifications@github.com> wrote:
>Looks like we have information that some ip/website is not available.
>```
>ERROR,http://93.63.179.120/AVCP/2014/Z3D0EB9B45-20150123120933813.xml,connect
>ETIMEDOUT,0,1017856
>ERROR,http://93.63.179.120/AVCP/2014/Z3F0D962BD-20150123090107938.xml,connect
>ETIMEDOUT,0,890627
>ERROR,http://93.63.179.120/AVCP/2014/Z3F120B602-20150122170018438.xml,connect
>ETIMEDOUT,0,1017854
>ERROR,http://93.63.179.120/AVCP/2014/Z400E3B55F-20150126101642438.xml,connect
>ETIMEDOUT,0,1017854
>ERROR,http://93.63.179.120/AVCP/2014/Z410D8354B-201412241119588.xml,connect
>ETIMEDOUT,0,1017855
>ERROR,http://93.63.179.120/AVCP/2014/Z4111A5BF3-20150122164145969.xml,connect
>ETIMEDOUT,0,1017855
>ERROR,http://93.63.179.120/AVCP/2014/Z440FA4373-20150122112439422.xml,connect
>ETIMEDOUT,0,890627
>ERROR,http://93.63.179.120/AVCP/2014/Z44109D413-20150123102107969.xml,connect
>ETIMEDOUT,0,1017854
>ERROR,http://93.63.179.120/AVCP/2014/Z450D8DF03-20150115111005213.xml,connect
>ETIMEDOUT,0,1017854
>ERROR,http://93.63.179.120/AVCP/2014/Z4512687FA-20150127104303031.xml,connect
>ETIMEDOUT,0,1017855
>ERROR,http://93.63.179.120/AVCP/2014/Z470E6998D-20150126095814609.xml,connect
>ETIMEDOUT,0,1017855
>ERROR,http://93.63.179.120/AVCP/2014/Z4710EE415-20150126111804266.xml,connect
>ETIMEDOUT,0,890627
>```
>If ANAC_url_generator.js have seen 3 ETIMEOUT for the same domain, stop
>trying to fetch documents from there. Drop them with different error
>(e.g. SITE_DOWN_DIDNT_TRY).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/synapta/public-contracts/issues/16

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by lonlylocly** [comment]
Agreed, option is fine for us.
