### ISSUE TITLE
Manage new labels

### ISSUE THREAD

**Issue by alemela** [synapta/public-contracts#39]
Manage the business entity labels but also those for comuni, using the Wikidata ones

**Comment by alemela** [comment]
- `rdfs:label` per la principale
- `skos:altLabel` per le alternative

**Comment by alemela** [comment]
Problems to resolve:

- we have bad labels for comuni, and we could use SPCData ones
- we have better lables for be and we should use

**Comment by giuseppefutia** [comment]
Stats for businessEntities
* Total: 28851
* Finded with the first check: 23724
* Finded adding the second check: 25326

Data saved locally

**Comment by giuseppefutia** [comment]
Data saved locally and uploaded to our triplestore
