### ISSUE TITLE
Remove CIG value from RDF when is absent

### ISSUE THREAD

**Issue by alemela** [synapta/public-contracts#61]
When a CIG is absent or hashed we put "CIG is missing (not valid)" during the triplification (see: https://github.com/synapta/public-contracts/blob/b4143dedefc62793c208b2ce20146f3c3f20226c/rdf/src/main/java/it/polito/nexa/pc/triplifiers/PublicContractsTriplifier.java#L62). It's better to not add at all the field, leaving only originalCIG.

**Comment by giuseppefutia** [comment]
Fixing on this branch with other features: https://github.com/synapta/public-contracts/tree/rdf-improvement/.

@alemela can I have a JSON file without the cig for testing the change?

**Comment by giuseppefutia** [comment]
See this pull request: https://github.com/synapta/public-contracts/pull/64
