### ISSUE TITLE
Recursive query error

### ISSUE THREAD

**Issue by ebergam** [synapta/public-contracts#83]
Any query I am trying to launch on the webservice gives the error `Error: parser error: Error: Syntax error: unexpected "`
[I am opening an issue here but I don't know if the project is still ongoing or if you are still maintaining it]

**Comment by alemela** [comment]
Ciao @ebergam !
The webservice is moved to https://contrattipubblici.org (for the sparql endpoint https://contrattipubblici.org/sparql)

**Comment by ebergam** [comment]
Ciao @alemela! I'll use it soon for a post-eartquake monitoring project :) 
Amazing job by the way!

**Comment by alemela** [comment]
Thanks @ebergam! At the moment online there are data until 2015, but in few days will appear all the contracts of 2016 and early 2017.

I know the monitoring project, so keep us informed with your work! Bye
